import React, { createContext, useState, useContext, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { supabase } from '../services/supabase';
import { DataService } from '../services/dataService';

export type Language = 'it' | 'en' | 'pt';



interface LocalizationContextProps {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
}

const translations = {
  it: {
    // Onboarding - Auth (STEP 0 - ora primo passo)
    'auth.title': 'Benvenuta in Viscare',
    'auth.subtitle': 'La tua spa-tech tascabile per la cura della pelle',
    'auth.name': 'Il tuo Nome',
    'auth.name_placeholder': 'Come ti chiami?',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signin': 'Accedi',
    'auth.signup': 'Registrati',
    'auth.toggle_signin': 'Hai già un account? Accedi',
    'auth.toggle_signup': 'Non hai un account? Registrati',
    'auth.or': 'oppure continua con',
    'auth.google': 'Google',
    'auth.apple': 'Apple',
    'auth.continue_apple': 'Continua con Apple',
    'auth.continue_google': 'Continua con Google',
    'auth.guest': 'Continua come Ospite',
    'auth.error_fill': 'Inserisci email e password.',
    'auth.error_name': 'Inserisci il tuo nome per continuare.',
    'auth.select_language': 'Seleziona la tua lingua',
    'auth.remember_me': 'Ricordami',
    'auth.forgot_password': 'Password dimenticata?',
    'auth.reset_password_title': 'Recupera Password',
    'auth.reset_password_desc': 'Inserisci la tua email registrata per ricevere il link di ripristino.',
    'auth.send_link': 'Invia Link',
    'auth.reset_success_title': 'Link Inviato!',
    'auth.reset_success_msg_mock': 'Dato che siamo in modalità test, puoi reimpostare la tua password adesso.',
    'auth.reset_success_msg_real': 'Abbiamo inviato un\'email con il link di ripristino per reimpostare la password.',
    'auth.new_password': 'Nuova Password',
    'auth.confirm_new_password': 'Conferma Nuova Password',
    'auth.passwords_must_match': 'Le password inserite non coincidono.',
    'auth.reset_success_done': 'Password reimpostata con successo! Ora puoi accedere con la nuova password.',

    // Onboarding - Disclaimer (STEP 1)
    'welcome.title': 'Viscare',
    'welcome.subtitle': 'La tua spa-tech tascabile',
    'welcome.value_prop1': 'Crea routine personalizzate basate sulle tue esigenze reali.',
    'welcome.value_prop2': 'Controlla la compatibilità dei principi attivi ed evita irritazioni.',
    'welcome.value_prop3': 'Genera la tua routine ottimale grazie all\'Intelligenza Artificiale.',
    'welcome.disclaimer_title': 'Dichiarazione di Non Responsabilità Medica',
    'welcome.disclaimer_text': 'Viscare non fornisce consigli medici o diagnosi. Le informazioni fornite dall\'app, inclusi i suggerimenti dell\'IA e i controlli di compatibilità, sono puramente a scopo informativo e di cura personale. Consulta sempre un dermatologo professionista per qualsiasi dubbio o problema persistente della pelle.',
    'welcome.accept_disclaimer': 'Accetta ed Continua',
    'welcome.next': 'Continua',

    // Onboarding - Quiz (STEP 2)
    'quiz.title': 'Quiz sulla Pelle',
    'quiz.subtitle': 'Aiutaci a conoscerti meglio',
    'quiz.age_question': 'Quanti anni hai?',
    'quiz.type_question': 'Qual è il tuo tipo di pelle?',
    'quiz.type_oily': 'Grassa',
    'quiz.type_dry': 'Secca',
    'quiz.type_combination': 'Mista',
    'quiz.type_normal': 'Normale',
    'quiz.sensitivity_question': 'La tua pelle è sensibile o si arrossa facilmente?',
    'quiz.sens_yes': 'Sì, molto sensibile',
    'quiz.sens_no': 'No, pelle resistente',
    'quiz.goals_question': 'Quali sono i tuoi obiettivi principali?',
    'quiz.goal_hydration': 'Idratazione',
    'quiz.goal_anti_aging': 'Antietà e Rughe',
    'quiz.goal_acne': 'Combattere l\'Acne',
    'quiz.goal_brightening': 'Illuminare / Macchie',
    'quiz.goal_barrier': 'Rafforzare la Barriera',
    'quiz.concerns_question': 'Quali sono le tue principali preoccupazioni?',
    'quiz.concern_redness': 'Arrossamento',
    'quiz.concern_dark_spots': 'Macchie scure',
    'quiz.concern_acne_scars': 'Cicatrici da acne',
    'quiz.concern_fine_lines': 'Linee sottili / Rughe',
    'quiz.concern_pores': 'Pori dilatati',
    'quiz.concern_dryness': 'Secchezza',
    'quiz.finish': 'Completa Quiz',

    // Onboarding - AI Recommendations (STEP 3)
    'ai_rec.title': 'Prodotti Consigliati per Te',
    'ai_rec.subtitle': 'In base al tuo profilo cutaneo, la nostra IA ha selezionato questi prodotti essenziali.',
    'ai_rec.adding': 'Aggiungendo al tuo armadietto...',
    'ai_rec.added': 'Aggiunto all\'armadietto!',
    'ai_rec.why': 'Perché questo prodotto?',
    'ai_rec.tip_best_time': 'Suggerimento Orario:',
    'ai_rec.add_all': "Aggiungi Tutti all'Armadietto",
    'ai_rec.loading': 'Analizzando il tuo profilo...',
    'ai_rec.step': 'Passo {n}',

    // Onboarding - Notifications (STEP 4)
    'notif.title': 'Resta Costante',
    'notif.text': 'Abilita le notifiche per ricordarti la routine AM (7:00), riapplicare l\'SPF (12:00) e la routine PM (22:00). La costanza è il segreto per una pelle radiosa.',
    'notif.enable': 'Abilita Notifiche',
    'notif.skip': 'Salta per Ora',

    // Onboarding - Welcome Screen (STEP 5)
    'welcome_screen.title': 'Benvenuta in Viscare,',
    'welcome_screen.message': 'Il tuo viaggio verso una pelle radiosa inizia ora! Abbiamo preparato tutto per te.',
    'welcome_screen.profile_summary': 'Il tuo profilo',
    'welcome_screen.skin_type': 'Tipo di pelle',
    'welcome_screen.goals': 'Obiettivi',
    'welcome_screen.goals_count': '{n} scelti',
    'welcome_screen.products_added': 'prodotti aggiunti al tuo armadietto',
    'welcome_screen.cta': 'Entra nel mio Viscare',
    'welcome_screen.motivation': '✨ Ogni passo conta. La tua pelle ti ringrazierà!',

    // Navigation
    'nav.back': 'Indietro',

    // Home / Today
    'home.greeting_morning': 'Buongiorno',
    'home.greeting_afternoon': 'Buon pomeriggio',
    'home.greeting_evening': 'Buonasera',
    'home.streak': 'giorni consecutivi',
    'home.subtitle': 'Pronta per la tua skin routine?',
    'home.skin_health': 'Salute della Pelle',
    'home.routine_am': 'Routine Mattutina',
    'home.routine_pm': 'Routine Serale',
    'home.upcoming_care': 'Prossimi Trattamenti',
    'home.favorites': 'I Miei Preferiti',
    'home.checklist_empty': 'Nessun prodotto in questa routine. Vai alla scheda "Routine" per configurarla.',
    'home.complete_task': 'Completato!',
    'home.incomplete_task': 'Segna come fatto',
    'home.create_routine': 'Crea Routine',
    'home.product_default': 'Prodotto',
    'home.brand_default': 'Marca',

    // Routine
    'routine.tab_title': 'Le Mie Routine',
    'routine.generate_ai': 'Genera con l\'IA',
    'routine.generating': 'Generando...',
    'routine.empty_cabinet_warning': 'Aggiungi prima dei prodotti nel tuo Armadietto per generare una routine!',
    'routine.error_quiz_not_completed': 'Completa prima il quiz sul profilo della pelle per generare la routine.',
    'routine.error_no_suitable_products': 'Nessun prodotto adatto nel tuo armadietto per questa routine.',
    'No suitable products found for this routine.': 'Nessun prodotto adatto nel tuo armadietto per questa routine.',
    'Skin profile quiz not completed yet.': 'Completa prima il quiz sul profilo della pelle per generare la routine.',
    'No products in cabinet.': 'Aggiungi prima dei prodotti nel tuo Armadietto per generare una routine!',
    'routine.order_hint': 'Trascina o usa le frecce per riordinare i passaggi. L\'IA ordina automaticamente in base alle regole dermatologiche.',
    'routine.am_label': 'Mattina (AM)',
    'routine.pm_label': 'Sera (PM)',
    'routine.delete_step': 'Rimuovi',
    'routine.add_step': 'Aggiungi Prodotto',
    'routine.empty_desc': 'Non ci sono passaggi configurati per questa routine. Aggiungi i prodotti dal tuo armadietto o genera con la nostra IA.',
    'routine.available_empty_desc': 'Tutti i prodotti del tuo armadietto sono già in questa routine o non hai ancora registrato prodotti.',

    // Products
    'products.title': 'Il Mio Armadietto',
    'products.subtitle': 'I tuoi prodotti personali',
    'products.search_placeholder': 'Cerca nel catalogo...',
    'products.manual_title': 'Aggiungi Prodotto Manualmente',
    'products.name': 'Nome del Prodotto',
    'products.brand': 'Marchio',
    'products.category': 'Categoria',
    'products.active_ingredients': 'Principi Attivi principali (separati da virgola)',
    'products.add_button': 'Aggiungi all\'Armadietto',
    'products.edit_button': 'Salva Modifiche',
    'products.delete': 'Elimina',
    'products.expiration': 'Scadenza (mesi dall\'apertura)',
    'products.opened': 'Aperto il',
    'products.limit_warning': 'Versione Gratuita: Limite di 5 prodotti raggiunto. Passa a Premium per sbloccare prigioni illimitate!',

    // Compatibility
    'compat.title': 'Verificatore di Compatibilità',
    'compat.safe': 'Compatibile',
    'compat.safe_desc': 'Tutti gli ingredienti attivi della tua routine lavorano in sinergia in modo sicuro!',
    'compat.caution': 'Attenzione',
    'compat.danger': 'Conflitto Rilevato',
    'compat.rules_title': 'Spiegazioni sulla Compatibilità',
    'compat.conflict_count': '{n} conflitto(i) di principi attivi rilevati in questa routine.',

    // Discover
    'discover.title': 'Esplora Ingredienti',
    'discover.subtitle': 'La scienza dietro la tua pelle',
    'discover.evidence': 'Livello di evidenza:',
    'discover.benefits': 'Benefici principali:',
    'discover.conflicts': 'Evitare con:',

    // Settings / Profile
    'settings.title': 'Profilo & Impostazioni',
    'settings.daily_reminders': 'Promemoria Giornalieri',
    'settings.spf_reapply': 'Riapplicazione SPF',
    'settings.language': 'Lingua',
    'settings.premium_status': 'Piano Attuale:',
    'settings.free': 'Gratuito',
    'settings.premium': 'Premium',
    'settings.upgrade': 'Passa a Premium',
    'settings.delete_account': 'Elimina Account',
    'settings.delete_warning': 'Attenzione: Questa azione è permanente e conforme alla normativa LGPD/GDPR. Eliminerà per sempre tutti i tuoi dati, rotine e account.',
    'settings.delete_confirm': 'Sì, Elimina Tutto',
    'settings.logout': 'Disconnetti',
    'settings.change_password': 'Cambia Password',
    'settings.privacy': 'Informativa sulla Privacy',
    'settings.terms': 'Termini di Servizio',

    // Tabs
    'tabs.today': 'Oggi',
    'tabs.routine': 'Routine',
    'tabs.products': 'Armadietto',
    'tabs.discover': 'Esplora',
    'tabs.agenda': 'Agenda',
    'tabs.settings': 'Impostazioni',

    // Paywall
    'paywall.title': 'Passa a Viscare Premium',
    'paywall.monthly_plan': 'Abbonamento Mensile',
    'paywall.monthly_desc': '7 giorni di prova gratuita, poi annulli quando vuoi',
    'paywall.yearly_plan': 'Abbonamento Annuale',
    'paywall.yearly_desc': '7 giorni di prova gratuita, pagamento annuale unico',
    'paywall.save_percent': 'Risparmi 37%',
    'paywall.subtitle': 'Sblocca tutto il potenziale per la cura della tua pelle',
    'paywall.feat_unlimited': 'Routine e Prodotti illimitati',
    'paywall.feat_ai': 'Analisi Facciale IA (2 scansioni/mese)',
    'paywall.feat_journal': 'Diario della pelle e monitoraggio fotografico',
    'paywall.feat_scan': 'Leitor Facciale IA esclusivo',
    'paywall.monthly': '{price} / mese',
    'paywall.yearly': '{price} / anno',
    'paywall.trial': 'Inizia Prova Gratuita di 7 Giorni',
    'paywall.restore': 'Ripristina Acquisti',
    'paywall.restoring': 'Ripristinando...',
    'paywall.close': 'Chiudi',
    'paywall.purchase_success_title': '✨ Benvenuta in Premium!',
    'paywall.purchase_success_msg': 'Grazie per esserti abbonata a Viscare Premium. Tutte le funzionalità sono ora sbloccate!',
    'paywall.restore_no_purchase': 'Nessun acquisto precedente trovato per questo account.',
    'paywall.restore_success': 'Acquisti ripristinati! Bentornata, cliente Premium.',
    'paywall.secure_badge': 'Pagamento 100% Sicuro',
    'paywall.ssl_badge': 'Crittografato SSL/TLS',
    'paywall.cancel_anytime': 'Annulla quando vuoi',
    'paywall.no_hidden_fees': 'Nessun costo nascosto',
    'paywall.currency_note': 'Prezzo nella tua valuta locale',
    'paywall.loading_price': 'Caricamento prezzi...',
    'paywall.price_month': 'al mese',
    'paywall.price_year': "all'anno",
    'paywall.store_info': 'Il pagamento viene elaborato in modo sicuro da Apple / Google. I dati della tua carta non vengono mai condivisi con noi.',
    'paywall.cancelled': 'Acquisto annullato.',
    'paywall.per_month_equivalent': '{price}/mese equivalente',

    // Alerts e mensagens comuns
    'common.cancel': 'Annulla',
    'common.ok': 'OK',
    'common.delete': 'Elimina',
    'common.error': 'Errore',
    'common.warning': 'Attenzione',
    'common.info': 'Informazione',
    'common.connection_error': 'Errore di connessione. Riprova.',

    'alert.disclaimer_required': 'Devi accettare il disclaimer per continuare.',
    'alert.invalid_age': 'Età non valida. Inserisci un numero tra 1 e 120.',
    'alert.fields_required': 'Nome e Marchio sono campi obbligatori.',
    'alert.delete_product_title': 'Elimina Prodotto',
    'alert.delete_product_msg': 'Sei sicuro di voler rimuovere questo prodotto? Verrà rimosso anche dalle tue routine.',
    'alert.limit_title': 'Limite Raggiunto',
    'alert.product_exists': 'Questo prodotto è già presente nella rotina.',
    'alert.cannot_delete_account': 'Impossibile eliminare l\'account. Riprova più tardi.',
    'alert.purchase_error': 'Impossibile completare l\'acquisto. Riprova.',
    'alert.streak_title': '🌟 Perfetto!',
    'alert.streak_msg': 'Hai completato la tua routine! Nuova serie: {n} giorni.',
    'alert.routine_error': 'Impossibile generare la routine. Riprova.',
    'alert.routine_success': 'Routine ottimizzata con successo secondo le regole dermatologiche!',
    'alert.auth_error': 'Errore di autenticazione. Verifica le credenziali.',

    'products.no_catalog_results': 'Nessun prodotto trovato nel catalogo.',
    'products.add_modal_title': 'Aggiungi Prodotto',
    'products.edit_modal_title': 'Modifica Prodotto',
    'products.empty_title': 'Nessun prodotto',
    'products.empty_msg': 'Il tuo armadietto è vuoto. Clicca sul "+" per aggiungere i tuoi prodotti.',

    // Accessibility
    'accessibility.move_up': 'Sposta in alto',
    'accessibility.move_down': 'Sposta in basso',
    'accessibility.remove_step': 'Rimuovi passo',
    'accessibility.delete_product': 'Elimina prodotto',
    'accessibility.close_paywall': 'Chiudi paywall',

    // Agenda
    'agenda.title': 'Mia Agenda',
    'agenda.subtitle': 'I tuoi prossimi trattamenti estetici.',
    'agenda.upcoming_treatments': 'Prossimi Trattamenti',
    'agenda.active_reminder': 'Promemoria Attivo',
    'agenda.reschedule': 'Riprogramma',
    'agenda.history': 'Cronologia',
    'agenda.treatment_deep_cleansing': 'Pulizia Viso Profonda',
    'agenda.treatment_peeling': 'Sessione di Peeling Chimico',
    'agenda.treatment_evaluation': 'Valutazione Facciale',
    'agenda.clinic_name': 'Clinica VisCare Premium',
    'agenda.day_14_jun': 'Venerdì, 14 Giugno',
    'agenda.day_27_jun': 'Giovedì, 27 Giugno',
    'agenda.day_01_jun': 'Sabato, 01 Giugno',
    'agenda.add_treatment': 'Aggiungi Trattamento',
    'agenda.delete_treatment': 'Elimina',
    'agenda.no_treatments': 'Nessun trattamento programmato',
    'agenda.schedule_cta': 'Programma Trattamento',
    'agenda.modal_title_add': 'Nuovo Appuntamento',
    'agenda.modal_title_edit': 'Riprogramma Trattamento',
    'agenda.placeholder_title': 'Nome del Trattamento',
    'agenda.placeholder_location': 'Clinica',
    'agenda.placeholder_time': 'Orario (es: 14:00 - 15:30)',
    'agenda.save': 'Salva',
    'today.manage_favorites': 'Gestisci Preferiti',
    'today.no_favorites': 'Nessun prodotto preferito selezionato.',
    'today.favorites_instructions': 'Tocca la stella sui tuoi prodotti per salvarli come preferiti.',
    'scan.title': 'Analisi Facciale IA',
    'scan.subtitle': 'Scatta o carica una foto per analizzare lo stato della tua pelle.',
    'scan.btn_camera': 'Scatta Foto',
    'scan.btn_gallery': 'Carica da Galleria',
    'scan.loading': 'Analisi in corso...',
    'scan.limit_reached': 'Limite mensile di 2 scansioni raggiunto!',
    'scan.premium_only': 'Funzionalità Premium',
    'scan.remaining': 'Analisi rimanenti questo mese: {n}',
    'scan.results_title': 'Risultati dell\'Analisi della Pelle',
    'scan.score_hydration': 'Livello di Idratazione (Più alto è meglio)',
    'scan.score_wrinkles': 'Segno di Rughe/Linee (Più alto % = Pelle più liscia e senza segni)',
    'scan.score_sensitivity': 'Livello di Sensibilità/Arrossamento (Minore % è meglio/pelle più resistente)',
    'scan.score_acne': 'Purezza della Pelle/Assenza di Acne (Più alto % = Pelle più pulita e senza brufoli)',
    'scan.diagnosis_title': 'Diagnosi dell\'IA e Routine',
    'scan.premium_required_msg': 'Questa funzionalità è disponibile solo per i clienti Premium.',
    'scan.active_ingredients_effect': 'Effetto dei tuoi prodotti attivi:',
    'scan.back_to_dashboard': 'Torna alla Dashboard',
    'scan.new_scan': 'Nuova Analisi'
  },
  en: {
    // Onboarding - Auth (STEP 0)
    'auth.title': 'Welcome to Viscare',
    'auth.subtitle': 'Your pocket spa-tech skincare companion',
    'auth.name': 'Your Name',
    'auth.name_placeholder': 'What\'s your name?',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signin': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.toggle_signin': 'Already have an account? Sign In',
    'auth.toggle_signup': 'Don\'t have an account? Sign Up',
    'auth.or': 'or continue with',
    'auth.google': 'Google',
    'auth.apple': 'Apple',
    'auth.continue_apple': 'Continue with Apple',
    'auth.continue_google': 'Continue with Google',
    'auth.guest': 'Continue as Guest',
    'auth.error_fill': 'Please enter email and password.',
    'auth.error_name': 'Please enter your name to continue.',
    'auth.select_language': 'Select your language',
    'auth.remember_me': 'Remember me',
    'auth.forgot_password': 'Forgot password?',
    'auth.reset_password_title': 'Reset Password',
    'auth.reset_password_desc': 'Enter your registered email to receive the reset link.',
    'auth.send_link': 'Send Link',
    'auth.reset_success_title': 'Link Sent!',
    'auth.reset_success_msg_mock': 'Since we are in test mode, you can reset your password right now.',
    'auth.reset_success_msg_real': 'We have sent an email with the recovery link to reset your password.',
    'auth.new_password': 'New Password',
    'auth.confirm_new_password': 'Confirm New Password',
    'auth.passwords_must_match': 'Passwords do not match.',
    'auth.reset_success_done': 'Password successfully reset! You can now sign in with your new password.',

    // Onboarding - Disclaimer (STEP 1)
    'welcome.title': 'Viscare',
    'welcome.subtitle': 'Your pocket spa-tech companion',
    'welcome.value_prop1': 'Create personalized skincare routines based on your real needs.',
    'welcome.value_prop2': 'Check active ingredients compatibility and avoid irritation.',
    'welcome.value_prop3': 'Generate your optimal routine powered by Artificial Intelligence.',
    'welcome.disclaimer_title': 'Medical Disclaimer',
    'welcome.disclaimer_text': 'Viscare does not provide medical advice or diagnosis. The information provided by the app, including AI suggestions and compatibility checks, is purely for informational and self-care purposes. Always consult a professional dermatologist for any concerns or persistent skin issues.',
    'welcome.accept_disclaimer': 'Accept & Continue',
    'welcome.next': 'Continue',

    // Onboarding - Quiz (STEP 2)
    'quiz.title': 'Skin Quiz',
    'quiz.subtitle': 'Help us know you better',
    'quiz.age_question': 'How old are you?',
    'quiz.type_question': 'What is your skin type?',
    'quiz.type_oily': 'Oily',
    'quiz.type_dry': 'Dry',
    'quiz.type_combination': 'Combination',
    'quiz.type_normal': 'Normal',
    'quiz.sensitivity_question': 'Is your skin sensitive or does it flush easily?',
    'quiz.sens_yes': 'Yes, very sensitive',
    'quiz.sens_no': 'No, resilient skin',
    'quiz.goals_question': 'What are your main goals?',
    'quiz.goal_hydration': 'Hydration',
    'quiz.goal_anti_aging': 'Anti-aging & Wrinkles',
    'quiz.goal_acne': 'Clear Acne',
    'quiz.goal_brightening': 'Brightening / Dark Spots',
    'quiz.goal_barrier': 'Strengthen Barrier',
    'quiz.concerns_question': 'What are your main concerns?',
    'quiz.concern_redness': 'Redness',
    'quiz.concern_dark_spots': 'Dark spots',
    'quiz.concern_acne_scars': 'Acne scars',
    'quiz.concern_fine_lines': 'Fine lines / Wrinkles',
    'quiz.concern_pores': 'Enlarged pores',
    'quiz.concern_dryness': 'Dryness',
    'quiz.finish': 'Finish Quiz',

    // Onboarding - AI Recommendations (STEP 3)
    'ai_rec.title': 'Products Recommended for You',
    'ai_rec.subtitle': 'Based on your skin profile, our AI has selected these essential products for you.',
    'ai_rec.adding': 'Adding to your cabinet...',
    'ai_rec.added': 'Added to cabinet!',
    'ai_rec.why': 'Why this product?',
    'ai_rec.tip_best_time': 'Recommended Time:',
    'ai_rec.add_all': 'Add All to Cabinet',
    'ai_rec.loading': 'Analyzing your profile...',
    'ai_rec.step': 'Step {n}',

    // Onboarding - Notifications (STEP 4)
    'notif.title': 'Stay Consistent',
    'notif.text': 'Enable notifications to remind you of your AM routine (7:00), SPF reapplication (12:00), and PM routine (22:00). Consistency is key to glowing skin.',
    'notif.enable': 'Enable Notifications',
    'notif.skip': 'Skip for Now',

    // Onboarding - Welcome Screen (STEP 5)
    'welcome_screen.title': 'Welcome to Viscare,',
    'welcome_screen.message': 'Your journey to radiant skin starts now! We\'ve set everything up for you.',
    'welcome_screen.profile_summary': 'Your profile',
    'welcome_screen.skin_type': 'Skin type',
    'welcome_screen.goals': 'Goals',
    'welcome_screen.goals_count': '{n} selected',
    'welcome_screen.products_added': 'products added to your cabinet',
    'welcome_screen.cta': 'Enter my Viscare',
    'welcome_screen.motivation': '✨ Every step counts. Your skin will thank you!',

    // Navigation
    'nav.back': 'Back',

    // Home / Today
    'home.greeting_morning': 'Good morning',
    'home.greeting_afternoon': 'Good afternoon',
    'home.greeting_evening': 'Good evening',
    'home.streak': 'day streak',
    'home.subtitle': 'Ready for your skin routine?',
    'home.skin_health': 'Skin Health',
    'home.routine_am': 'Morning Routine',
    'home.routine_pm': 'Evening Routine',
    'home.upcoming_care': 'Upcoming Care',
    'home.favorites': 'My Favorites',
    'home.checklist_empty': 'No products in this routine. Go to "Routine" tab to set it up.',
    'home.complete_task': 'Completed!',
    'home.incomplete_task': 'Mark as done',
    'home.create_routine': 'Create Routine',
    'home.product_default': 'Product',
    'home.brand_default': 'Brand',

    // Routine
    'routine.tab_title': 'My Routines',
    'routine.generate_ai': 'Generate with AI',
    'routine.generating': 'Generating...',
    'routine.empty_cabinet_warning': 'Add some products to your Cabinet first to generate a routine!',
    'routine.error_quiz_not_completed': 'Please complete the skin profile quiz first to generate a routine.',
    'routine.error_no_suitable_products': 'No suitable products in your cabinet found for this routine.',
    'No suitable products found for this routine.': 'No suitable products in your cabinet found for this routine.',
    'Skin profile quiz not completed yet.': 'Please complete the skin profile quiz first to generate a routine.',
    'No products in cabinet.': 'Add some products to your Cabinet first to generate a routine!',
    'routine.order_hint': 'Drag or use arrows to reorder steps. AI orders automatically based on dermatological rules.',
    'routine.am_label': 'Morning (AM)',
    'routine.pm_label': 'Night (PM)',
    'routine.delete_step': 'Remove',
    'routine.add_step': 'Add Product',
    'routine.empty_desc': 'There are no steps configured for this routine. Add products from your cabinet or generate with our AI.',
    'routine.available_empty_desc': 'All products in your cabinet are already in this routine or you have not registered products yet.',

    // Products
    'products.title': 'My Cabinet',
    'products.subtitle': 'Your personal skincare products',
    'products.search_placeholder': 'Search in catalog...',
    'products.manual_title': 'Add Product Manually',
    'products.name': 'Product Name',
    'products.brand': 'Brand',
    'products.category': 'Category',
    'products.active_ingredients': 'Active Ingredients (comma separated)',
    'products.add_button': 'Add to Cabinet',
    'products.edit_button': 'Save Changes',
    'products.delete': 'Delete',
    'products.expiration': 'Expiration (months after opening)',
    'products.opened': 'Opened on',
    'products.limit_warning': 'Free Tier: Limit of 5 products reached. Upgrade to Premium for unlimited cabinet size!',

    // Compatibility
    'compat.title': 'Compatibility Checker',
    'compat.safe': 'Compatible',
    'compat.safe_desc': 'All active ingredients in your routine work together safely!',
    'compat.caution': 'Caution',
    'compat.danger': 'Conflict Detected',
    'compat.rules_title': 'Compatibility Explanations',
    'compat.conflict_count': '{n} active ingredient conflict(s) detected in this routine.',

    // Discover
    'discover.title': 'Explore Ingredients',
    'discover.subtitle': 'The science behind your skin',
    'discover.evidence': 'Evidence level:',
    'discover.benefits': 'Main benefits:',
    'discover.conflicts': 'Avoid combining with:',

    // Settings / Profile
    'settings.title': 'Profile & Settings',
    'settings.daily_reminders': 'Daily Reminders',
    'settings.spf_reapply': 'SPF Reapplication',
    'settings.language': 'Language',
    'settings.premium_status': 'Current Plan:',
    'settings.free': 'Free',
    'settings.premium': 'Premium',
    'settings.upgrade': 'Upgrade to Premium',
    'settings.delete_account': 'Delete Account',
    'settings.delete_warning': 'Warning: This action is permanent and GDPR/LGPD compliant. It will forever delete all your data, routines, and account.',
    'settings.delete_confirm': 'Yes, Delete Everything',
    'settings.logout': 'Log Out',
    'settings.change_password': 'Change Password',
    'settings.privacy': 'Privacy Policy',
    'settings.terms': 'Terms of Service',

    // Tabs
    'tabs.today': 'Today',
    'tabs.routine': 'Routine',
    'tabs.products': 'Cabinet',
    'tabs.discover': 'Explore',
    'tabs.agenda': 'Agenda',
    'tabs.settings': 'Settings',

    // Alerts and common messages
    'common.cancel': 'Cancel',
    'common.ok': 'OK',
    'common.delete': 'Delete',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.connection_error': 'Connection error. Please try again.',

    'alert.disclaimer_required': 'You must accept the disclaimer to continue.',
    'alert.invalid_age': 'Invalid age. Please enter a number between 1 and 120.',
    'alert.fields_required': 'Name and Brand are required fields.',
    'alert.delete_product_title': 'Delete Product',
    'alert.delete_product_msg': 'Are you sure you want to remove this product? It will also be removed from your routines.',
    'alert.limit_title': 'Limit Reached',
    'alert.product_exists': 'This product is already in the routine.',
    'alert.cannot_delete_account': 'Unable to delete account. Please try again later.',
    'alert.purchase_error': 'Unable to complete purchase. Please try again.',
    'alert.streak_title': '🌟 Amazing!',
    'alert.streak_msg': 'You completed your routine! New streak: {n} days.',
    'alert.routine_error': 'Unable to generate routine. Please try again.',
    'alert.routine_success': 'Routine successfully optimized according to dermatological rules!',
    'alert.auth_error': 'Authentication error. Please check your credentials.',

    'products.no_catalog_results': 'No products found in catalog.',
    'products.add_modal_title': 'Add Product',
    'products.edit_modal_title': 'Edit Product',
    'products.empty_title': 'No products',
    'products.empty_msg': 'Your cabinet is empty. Tap the "+" button to add your products.',

    // Accessibility
    'accessibility.move_up': 'Move up',
    'accessibility.move_down': 'Move down',
    'accessibility.remove_step': 'Remove step',
    'accessibility.delete_product': 'Delete product',
    'accessibility.close_paywall': 'Close paywall',

    // Paywall EN
    'paywall.title': 'Upgrade to Viscare Premium',
    'paywall.monthly_plan': 'Monthly Plan',
    'paywall.monthly_desc': '7-day free trial, cancel anytime',
    'paywall.yearly_plan': 'Annual Plan',
    'paywall.yearly_desc': '7-day free trial, single annual payment',
    'paywall.save_percent': 'Save 37%',
    'paywall.subtitle': 'Unlock the full potential for your skin care',
    'paywall.feat_unlimited': 'Unlimited routines and products',
    'paywall.feat_ai': 'AI Facial Analysis (2 scans/month)',
    'paywall.feat_journal': 'Skin journal and photo progress tracking',
    'paywall.feat_scan': 'Exclusive AI Facial Reader',
    'paywall.monthly': '{price} / month',
    'paywall.yearly': '{price} / year',
    'paywall.trial': 'Start 7-Day Free Trial',
    'paywall.restore': 'Restore Purchases',
    'paywall.restoring': 'Restoring...',
    'paywall.close': 'Close',
    'paywall.purchase_success_title': '✨ Welcome to Premium!',
    'paywall.purchase_success_msg': 'Thank you for subscribing to Viscare Premium. All features are now unlocked!',
    'paywall.restore_no_purchase': 'No previous purchases found for this account.',
    'paywall.restore_success': 'Purchases restored! Welcome back, Premium member.',
    'paywall.secure_badge': '100% Secure Payment',
    'paywall.ssl_badge': 'SSL/TLS Encrypted',
    'paywall.cancel_anytime': 'Cancel anytime',
    'paywall.no_hidden_fees': 'No hidden fees',
    'paywall.currency_note': 'Price shown in your local currency',
    'paywall.loading_price': 'Loading prices...',
    'paywall.price_month': 'per month',
    'paywall.price_year': 'per year',
    'paywall.store_info': 'Payment securely processed by Apple / Google. Your card details are never shared with us.',
    'paywall.cancelled': 'Purchase cancelled.',
    'paywall.per_month_equivalent': '{price}/month equivalent',

    // Agenda
    'agenda.title': 'My Schedule',
    'agenda.subtitle': 'Your upcoming aesthetic treatments.',
    'agenda.upcoming_treatments': 'Upcoming Treatments',
    'agenda.active_reminder': 'Active Reminder',
    'agenda.reschedule': 'Reschedule',
    'agenda.history': 'History',
    'agenda.treatment_deep_cleansing': 'Deep Facial Cleansing',
    'agenda.treatment_peeling': 'Chemical Peeling Session',
    'agenda.treatment_evaluation': 'Facial Evaluation',
    'agenda.clinic_name': 'VisCare Premium Clinic',
    'agenda.day_14_jun': 'Friday, June 14',
    'agenda.day_27_jun': 'Thursday, June 27',
    'agenda.day_01_jun': 'Saturday, June 1',
    'agenda.add_treatment': 'Add Treatment',
    'agenda.delete_treatment': 'Delete',
    'agenda.no_treatments': 'No treatments scheduled',
    'agenda.schedule_cta': 'Schedule Treatment',
    'agenda.modal_title_add': 'New Appointment',
    'agenda.modal_title_edit': 'Reschedule Treatment',
    'agenda.placeholder_title': 'Treatment Name',
    'agenda.placeholder_location': 'Clinic',
    'agenda.placeholder_time': 'Time (e.g. 14:00 - 15:30)',
    'agenda.save': 'Save',
    'today.manage_favorites': 'Manage Favorites',
    'today.no_favorites': 'No favorite products selected.',
    'today.favorites_instructions': 'Tap the star on your products to save them as favorites.',
    'scan.title': 'AI Facial Analysis',
    'scan.subtitle': 'Take or upload a photo to analyze your skin state.',
    'scan.btn_camera': 'Take Photo',
    'scan.btn_gallery': 'Choose from Gallery',
    'scan.loading': 'Analyzing your skin...',
    'scan.limit_reached': 'Monthly limit of 2 scans reached!',
    'scan.premium_only': 'Premium Feature',
    'scan.remaining': 'Scans remaining this month: {n}',
    'scan.results_title': 'Skin Analysis Results',
    'scan.score_hydration': 'Hydration Level (Higher is better)',
    'scan.score_wrinkles': 'Wrinkles/Lines Score (Higher % = Smoother skin with fewer marks)',
    'scan.score_sensitivity': 'Sensitivity/Redness Level (Lower % is better/more resilient skin)',
    'scan.score_acne': 'Skin Purity/Absence of Acne (Higher % = Cleaner skin without blemishes)',
    'scan.diagnosis_title': 'AI Diagnosis & Routine',
    'scan.premium_required_msg': 'This feature is only available for Premium subscribers.',
    'scan.active_ingredients_effect': 'Effect of your active products:',
    'scan.back_to_dashboard': 'Back to Dashboard',
    'scan.new_scan': 'New Scan'
  },
  pt: {
    // Onboarding - Auth (STEP 0)
    'auth.title': 'Bem-vinda ao Viscare',
    'auth.subtitle': 'Sua spa-tech de bolso para cuidados com a pele',
    'auth.name': 'Seu Nome',
    'auth.name_placeholder': 'Qual é o seu nome?',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.signin': 'Entrar',
    'auth.signup': 'Cadastrar',
    'auth.toggle_signin': 'Já tem uma conta? Entrar',
    'auth.toggle_signup': 'Não tem uma conta? Cadastrar',
    'auth.or': 'ou continue com',
    'auth.google': 'Google',
    'auth.apple': 'Apple',
    'auth.continue_apple': 'Continuar com Apple',
    'auth.continue_google': 'Continuar com Google',
    'auth.guest': 'Continuar como Convidada',
    'auth.error_fill': 'Preencha o e-mail e a senha.',
    'auth.error_name': 'Insira seu nome para continuar.',
    'auth.select_language': 'Selecione seu idioma',
    'auth.remember_me': 'Lembrar de mim',
    'auth.forgot_password': 'Esqueceu a senha?',
    'auth.reset_password_title': 'Recuperar Senha',
    'auth.reset_password_desc': 'Insira seu e-mail cadastrado para receber o link de redefinição de senha.',
    'auth.send_link': 'Enviar Link',
    'auth.reset_success_title': 'Link Enviado!',
    'auth.reset_success_msg_mock': 'Como estamos no modo de teste, você pode redefinir sua senha agora mesmo.',
    'auth.reset_success_msg_real': 'Enviamos um e-mail com o link de recuperação para você redefinir sua senha.',
    'auth.new_password': 'Nova Senha',
    'auth.confirm_new_password': 'Confirmar Nova Senha',
    'auth.passwords_must_match': 'As senhas digitadas não coincidem.',
    'auth.reset_success_done': 'Senha redefinida com sucesso! Agora você pode entrar com a nova senha.',

    // Onboarding - Disclaimer (STEP 1)
    'welcome.title': 'Viscare',
    'welcome.subtitle': 'Sua spa-tech de bolso',
    'welcome.value_prop1': 'Crie rotinas de cuidados personalizadas com base em suas necessidades reais.',
    'welcome.value_prop2': 'Verifique a compatibilidade dos ingredientes ativos e evite irritações.',
    'welcome.value_prop3': 'Gere sua rotina ideal potencializada por Inteligência Artificial.',
    'welcome.disclaimer_title': 'Aviso de Isenção de Responsabilidade Médica',
    'welcome.disclaimer_text': 'O Viscare não fornece aconselhamento médico ou diagnóstico. As informações fornecidas pelo aplicativo, incluindo sugestões de IA e verificações de compatibilidade, são puramente para fins informativos e de autocuidado. Sempre consulte um dermatologista profissional para qualquer dúvida ou problema persistente na pele.',
    'welcome.accept_disclaimer': 'Aceitar e Continuar',
    'welcome.next': 'Continuar',

    // Onboarding - Quiz (STEP 2)
    'quiz.title': 'Quiz da Pele',
    'quiz.subtitle': 'Ajude-nos a te conhecer melhor',
    'quiz.age_question': 'Qual é a sua idade?',
    'quiz.type_question': 'Qual é o seu tipo de pele?',
    'quiz.type_oily': 'Oleosa',
    'quiz.type_dry': 'Seca',
    'quiz.type_combination': 'Mista',
    'quiz.type_normal': 'Normal',
    'quiz.sensitivity_question': 'Sua pele é sensível ou fica vermelha facilmente?',
    'quiz.sens_yes': 'Sim, muito sensível',
    'quiz.sens_no': 'Não, pele resistente',
    'quiz.goals_question': 'Quais são os seus principais objetivos?',
    'quiz.goal_hydration': 'Hidratação',
    'quiz.goal_anti_aging': 'Antienvelhecimento / Rugas',
    'quiz.goal_acne': 'Combater Acne',
    'quiz.goal_brightening': 'Iluminar / Manchas',
    'quiz.goal_barrier': 'Fortalecer Barreira',
    'quiz.concerns_question': 'Quais são as suas principais preocupações?',
    'quiz.concern_redness': 'Vermelhidão',
    'quiz.concern_dark_spots': 'Manchas escuras',
    'quiz.concern_acne_scars': 'Cicatrizes de acne',
    'quiz.concern_fine_lines': 'Linhas finas / Rugas',
    'quiz.concern_pores': 'Poros dilatados',
    'quiz.concern_dryness': 'Ressecamento',
    'quiz.finish': 'Concluir Quiz',

    // Onboarding - AI Recommendations (STEP 3)
    'ai_rec.title': 'Produtos Recomendados para Você',
    'ai_rec.subtitle': 'Com base no seu perfil de pele, nossa IA selecionou estes produtos essenciais para você.',
    'ai_rec.adding': 'Adicionando ao seu armário...',
    'ai_rec.added': 'Adicionado ao armário!',
    'ai_rec.why': 'Por que este produto?',
    'ai_rec.tip_best_time': 'Horário Recomendado:',
    'ai_rec.add_all': 'Adicionar Todos ao Armário',
    'ai_rec.loading': 'Analisando seu perfil...',
    'ai_rec.step': 'Passo {n}',

    // Onboarding - Notifications (STEP 4)
    'notif.title': 'Mantenha a Constância',
    'notif.text': 'Ative as notificações para lembrá-la da rotina matinal (7:00), reaplicação do protetor solar (12:00) e rotina noturna (22:00). A constância é o segredo para uma pele radiante.',
    'notif.enable': 'Ativar Notificações',
    'notif.skip': 'Pular por Enquanto',

    // Onboarding - Welcome Screen (STEP 5)
    'welcome_screen.title': 'Bem-vinda ao Viscare,',
    'welcome_screen.message': 'Sua jornada para uma pele radiante começa agora! Preparamos tudo para você.',
    'welcome_screen.profile_summary': 'Seu perfil',
    'welcome_screen.skin_type': 'Tipo de pele',
    'welcome_screen.goals': 'Objetivos',
    'welcome_screen.goals_count': '{n} selecionados',
    'welcome_screen.products_added': 'produtos adicionados ao seu armário',
    'welcome_screen.cta': 'Entrar no meu Viscare',
    'welcome_screen.motivation': '✨ Cada passo conta. Sua pele vai agradecer!',

    // Navigation
    'nav.back': 'Voltar',

    // Home / Today
    'home.greeting_morning': 'Bom dia',
    'home.greeting_afternoon': 'Boa tarde',
    'home.greeting_evening': 'Boa noite',
    'home.streak': 'dias seguidos',
    'home.subtitle': 'Pronta para sua rotina de pele?',
    'home.skin_health': 'Saúde da Pele',
    'home.routine_am': 'Rotina da Manhã',
    'home.routine_pm': 'Rotina da Noite',
    'home.upcoming_care': 'Próximos Cuidados',
    'home.favorites': 'Meus Favoritos',
    'home.checklist_empty': 'Nenhum produto nesta rotina. Vá para a aba "Rotina" para configurá-la.',
    'home.complete_task': 'Concluído!',
    'home.incomplete_task': 'Marcar como feito',
    'home.create_routine': 'Criar Rotina',
    'home.product_default': 'Produto',
    'home.brand_default': 'Marca',

    // Routine
    'routine.tab_title': 'Minhas Rotinas',
    'routine.generate_ai': 'Gerar com IA',
    'routine.generating': 'Gerando...',
    'routine.empty_cabinet_warning': 'Adicione alguns produtos ao seu Armário primeiro para gerar uma rotina!',
    'routine.error_quiz_not_completed': 'Por favor, conclua o quiz de perfil de pele primeiro para gerar uma rotina.',
    'routine.error_no_suitable_products': 'Nenhum produto adequado encontrado no seu armário para esta rotina.',
    'No suitable products found for this routine.': 'Nenhum produto adequado encontrado no seu armário para esta rotina.',
    'Skin profile quiz not completed yet.': 'Por favor, conclua o quiz de perfil de pele primeiro para gerar uma rotina.',
    'No products in cabinet.': 'Adicione alguns produtos ao seu Armário primeiro para gerar uma rotina!',
    'routine.order_hint': 'Arraste ou use as setas para reordenar os passos. A IA ordena automaticamente com base em regras dermatológicas.',
    'routine.am_label': 'Manhã (AM)',
    'routine.pm_label': 'Noite (PM)',
    'routine.delete_step': 'Remover',
    'routine.add_step': 'Adicionar Produto',
    'routine.empty_desc': 'Não há passos configurados para esta rotina. Adicione produtos do seu armário ou gere com a nossa IA.',
    'routine.available_empty_desc': 'Todos os produtos do seu armário já estão nesta rotina ou você ainda não cadastrou produtos.',

    // Products
    'products.title': 'Meu Armário',
    'products.subtitle': 'Seus produtos pessoais de skincare',
    'products.search_placeholder': 'Buscar no catálogo...',
    'products.manual_title': 'Adicionar Produto Manualmente',
    'products.name': 'Nome do Produto',
    'products.brand': 'Marca',
    'products.category': 'Categoria',
    'products.active_ingredients': 'Princípios Ativos principais (separados por vírgula)',
    'products.add_button': 'Adicionar ao Armário',
    'products.edit_button': 'Salvar Alterações',
    'products.delete': 'Excluir',
    'products.expiration': 'Validade (meses após aberto)',
    'products.opened': 'Aberto em',
    'products.limit_warning': 'Versão Gratuita: Limite de 5 produtos atingido. Mude para o Premium para armário ilimitado!',

    // Compatibility
    'compat.title': 'Verificador de Compatibilidade',
    'compat.safe': 'Compatível',
    'compat.safe_desc': 'Todos os ingredientes ativos em sua rotina trabalham juntos com segurança!',
    'compat.caution': 'Atenção',
    'compat.danger': 'Conflito Detectado',
    'compat.rules_title': 'Explicações sobre Compatibilidade',
    'compat.conflict_count': '{n} conflito(s) de ingrediente ativo detectados nesta rotina.',

    // Discover
    'discover.title': 'Explorar Ingredientes',
    'discover.subtitle': 'A ciência por trás da sua pele',
    'discover.evidence': 'Nível de evidência:',
    'discover.benefits': 'Principais benefícios:',
    'discover.conflicts': 'Evitar combinar com:',

    // Settings / Profile
    'settings.title': 'Perfil & Configurações',
    'settings.daily_reminders': 'Lembretes Diários',
    'settings.spf_reapply': 'Reaplicação de SPF',
    'settings.language': 'Idioma',
    'settings.premium_status': 'Plano Atual:',
    'settings.free': 'Gratuito',
    'settings.premium': 'Premium',
    'settings.upgrade': 'Mudar para Premium',
    'settings.delete_account': 'Excluir Conta',
    'settings.delete_warning': 'Aviso: Esta ação é permanente e cumpre com as regras da LGPD/GDPR. Excluirá para sempre todos os seus dados, rotinas e conta.',
    'settings.delete_confirm': 'Sim, Excluir Tudo',
    'settings.logout': 'Sair',
    'settings.change_password': 'Trocar Senha',
    'settings.privacy': 'Política de Privacidade',
    'settings.terms': 'Termos de Serviço',

    // Tabs
    'tabs.today': 'Hoje',
    'tabs.routine': 'Rotina',
    'tabs.products': 'Armário',
    'tabs.discover': 'Explorar',
    'tabs.agenda': 'Agenda',
    'tabs.settings': 'Configurações',

    // Alerts e mensagens comuns
    'common.cancel': 'Cancelar',
    'common.ok': 'OK',
    'common.delete': 'Excluir',
    'common.error': 'Erro',
    'common.warning': 'Atenção',
    'common.info': 'Info',
    'common.connection_error': 'Erro de conexão. Tente novamente.',

    'alert.disclaimer_required': 'Você precisa aceitar o aviso para continuar.',
    'alert.invalid_age': 'Idade inválida. Insira um número entre 1 e 120.',
    'alert.fields_required': 'Nome e Marca são campos obrigatórios.',
    'alert.delete_product_title': 'Excluir Produto',
    'alert.delete_product_msg': 'Tem certeza que deseja remover este produto? Ele também será removido das suas rotinas.',
    'alert.limit_title': 'Limite Atingido',
    'alert.product_exists': 'Este produto já está presente na rotina.',
    'alert.cannot_delete_account': 'Não foi possível excluir a conta. Tente novamente mais tarde.',
    'alert.purchase_error': 'Não foi possível concluir a compra. Tente novamente.',
    'alert.streak_title': '🌟 Perfeito!',
    'alert.streak_msg': 'Você completou sua rotina! Nova sequência: {n} dias.',
    'alert.routine_error': 'Não foi possível gerar a rotina. Tente novamente.',
    'alert.routine_success': 'Rotina otimizada com sucesso segundo as regras dermatológicas!',
    'alert.auth_error': 'Erro de autenticação. Verifique suas credenciais.',

    'products.no_catalog_results': 'Nenhum produto encontrado no catálogo.',
    'products.add_modal_title': 'Adicionar Produto',
    'products.edit_modal_title': 'Editar Produto',
    'products.empty_title': 'Nenhum produto',
    'products.empty_msg': 'Seu armário está vazio. Toque no "+" para adicionar seus produtos.',

    // Accessibility
    'accessibility.move_up': 'Mover para cima',
    'accessibility.move_down': 'Mover para baixo',
    'accessibility.remove_step': 'Remover passo',
    'accessibility.delete_product': 'Excluir produto',
    'accessibility.close_paywall': 'Fechar paywall',

    // Agenda
    'agenda.title': 'Minha Agenda',
    'agenda.subtitle': 'Seus próximos tratamentos estéticos.',
    'agenda.upcoming_treatments': 'Próximos Tratamentos',
    'agenda.active_reminder': 'Lembrete Ativo',
    'agenda.reschedule': 'Reagendar',
    'agenda.history': 'Histórico',
    'agenda.treatment_deep_cleansing': 'Limpeza de Pele Profunda',
    'agenda.treatment_peeling': 'Sessão de Peeling Químico',
    'agenda.treatment_evaluation': 'Avaliação Facial',
    'agenda.clinic_name': 'Clínica VisCare Premium',
    'agenda.day_14_jun': 'Sexta-feira, 14 de Junho',
    'agenda.day_27_jun': 'Quinta-feira, 27 de Junho',
    'agenda.day_01_jun': 'Sábado, 01 de Junho',
    'agenda.add_treatment': 'Adicionar Tratamento',
    'agenda.delete_treatment': 'Excluir',
    'agenda.no_treatments': 'Nenhum tratamento agendado',
    'agenda.schedule_cta': 'Agendar Tratamento',
    'agenda.modal_title_add': 'Novo Agendamento',
    'agenda.modal_title_edit': 'Reagendar Tratamento',
    'agenda.placeholder_title': 'Nome do Tratamento',
    'agenda.placeholder_location': 'Clínica',
    'agenda.placeholder_time': 'Horário (ex: 14:00 - 15:30)',
    'agenda.save': 'Salvar',

    // Paywall PT
    'paywall.title': 'Seja Premium no Viscare',
    'paywall.monthly_plan': 'Plano Mensal',
    'paywall.monthly_desc': '7 dias grátis, cancele quando quiser',
    'paywall.yearly_plan': 'Plano Anual',
    'paywall.yearly_desc': '7 dias grátis, pagamento único anual',
    'paywall.save_percent': 'Economize 37%',
    'paywall.subtitle': 'Desbloqueie todo o potencial para o cuidado da sua pele',
    'paywall.feat_unlimited': 'Rotinas e Produtos ilimitados',
    'paywall.feat_ai': 'Análise Facial IA (2 análises/mês)',
    'paywall.feat_journal': 'Diário da pele e acompanhamento fotográfico',
    'paywall.feat_scan': 'Leitor Facial IA exclusivo',
    'paywall.monthly': '{price} / mês',
    'paywall.yearly': '{price} / ano',
    'paywall.trial': 'Começar 7 Dias Grátis',
    'paywall.restore': 'Restaurar Compras',
    'paywall.restoring': 'Restaurando...',
    'paywall.close': 'Fechar',
    'paywall.purchase_success_title': '✨ Bem-vinda ao Premium!',
    'paywall.purchase_success_msg': 'Obrigada por assinar o Viscare Premium. Todos os recursos foram desbloqueados!',
    'paywall.restore_no_purchase': 'Nenhuma compra anterior encontrada nesta conta.',
    'paywall.restore_success': 'Compras restauradas! Bem-vinda de volta, cliente Premium.',
    'paywall.secure_badge': 'Pagamento 100% Seguro',
    'paywall.ssl_badge': 'Criptografado com SSL/TLS',
    'paywall.cancel_anytime': 'Cancele quando quiser',
    'paywall.no_hidden_fees': 'Sem taxas ocultas',
    'paywall.currency_note': 'Preço exibido na sua moeda local',
    'paywall.loading_price': 'Carregando preços...',
    'paywall.price_month': 'por mês',
    'paywall.price_year': 'por ano',
    'paywall.store_info': 'Pagamento processado com segurança pela Apple / Google. Seus dados de cartão nunca são compartilhados conosco.',
    'paywall.cancelled': 'Compra cancelada.',
    'paywall.per_month_equivalent': '{price}/mês equivalente',

    'today.manage_favorites': 'Gerenciar Favoritos',
    'today.no_favorites': 'Nenhum produto favorito selecionado.',
    'today.favorites_instructions': 'Toque na estrela em seus produtos para salvá-los como favoritos.',
    'scan.title': 'Análise Facial IA',
    'scan.subtitle': 'Tire ou envie uma foto para analisar o estado da sua pele.',
    'scan.btn_camera': 'Tirar Foto',
    'scan.btn_gallery': 'Escolher da Galeria',
    'scan.loading': 'Analisando sua pele...',
    'scan.limit_reached': 'Limite mensal de 2 análises atingido!',
    'scan.premium_only': 'Recurso Premium',
    'scan.remaining': 'Análises restantes este mês: {n}',
    'scan.results_title': 'Resultados da Análise de Pele',
    'scan.score_hydration': 'Nível de Hidratação (Mais é melhor)',
    'scan.score_wrinkles': 'Sinal de Rugas/Linhas (Maior % = Pele mais Lisa e sem marcas)',
    'scan.score_sensitivity': 'Nível de Sensibilidade/Vermelhidão (Menor % é melhor/pele mais resistente)',
    'scan.score_acne': 'Pureza da Pele/Ausência de Acne (Maior % = Pele mais limpa e sem espinhas)',
    'scan.diagnosis_title': 'Diagnóstico da IA e Rotina',
    'scan.premium_required_msg': 'Esta funcionalidade está disponível apenas para clientes Premium.',
    'scan.active_ingredients_effect': 'Efeito dos seus produtos ativos:',
    'scan.back_to_dashboard': 'Voltar ao Painel',
    'scan.new_scan': 'Nova Análise'
  }
};

const LocalizationContext = createContext<LocalizationContextProps | undefined>(undefined);

export const LocalizationProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('it');

  useEffect(() => {
    // Carregar idioma salvo ao iniciar
    const loadLanguage = async () => {
      try {
        const savedLang = await AsyncStorage.getItem('viscare_language');
        if (savedLang === 'it' || savedLang === 'en' || savedLang === 'pt') {
          setLanguageState(savedLang);
        }
      } catch (e) {
        console.warn('Erro ao carregar idioma', e);
      }
    };
    loadLanguage();
  }, []);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    try {
      await AsyncStorage.setItem('viscare_language', lang);
      // Sincronizar com perfil se logado no Supabase
      const { data } = await supabase.auth.getSession();
      if (data.session?.user?.id) {
        await DataService.updateProfile(data.session.user.id, { language: lang });
      }
    } catch (e) {
      console.warn('Erro ao salvar idioma', e);
    }
  };

  const t = (key: string): string => {
    const dict = translations[language] || translations['it'];
    return dict[key as keyof typeof dict] || key;
  };

  return (
    <LocalizationContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LocalizationContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LocalizationContext);
  if (!context) {
    throw new Error('useTranslation deve ser utilizado dentro de um LocalizationProvider');
  }
  return context;
};
